### login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "user@gmail.com",
    "password" : "user"
}

### login admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "afif@gmail.com",
    "password" : "afif"
}

### me 
GET http://localhost:5000/me

### me 
delete http://localhost:5000/logOut
